name: fluteer_app1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0+1 # Verifica en pub.dev si hay una versi칩n m치s reciente
  path: ^1.8.0 # Verifica en pub.dev si hay una versi칩n m치s reciente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
